local ldPipe = table.deepcopy(data.raw["pipe"]["pipe"])

ldPipe.name = "ld-pipe"
ldPipe.minable = { mining_time = 0.1, result = "ld-pipe" }
ldPipe.fluid_box.pipe_connections = {
    { direction = defines.direction.north, position = { 0, 0 }, connection_category = "ld-pipe" },
    { direction = defines.direction.east, position = { 0, 0 }, connection_category = "ld-pipe" },
    { direction = defines.direction.south, position = { 0, 0 }, connection_category = "ld-pipe" },
    { direction = defines.direction.west, position = { 0, 0 }, connection_category = "ld-pipe" },
}
ldPipe.fluid_box.max_pipeline_extent = 320000
ldPipe.pictures = {
    straight_vertical_single = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-straight-vertical-single.png",
        priority = "extra-high",
        width = 160,
        height = 160,
        scale = 0.5,
    },
      straight_vertical = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-straight-vertical.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      straight_vertical_window = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-straight-vertical-window.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      straight_horizontal_window = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-straight-horizontal-window.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      straight_horizontal = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-straight-horizontal.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      corner_up_right = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-corner-up-right.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      corner_up_left = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-corner-up-left.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      corner_down_right = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-corner-down-right.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      corner_down_left = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-corner-down-left.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      t_up = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-t-up.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      t_down = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-t-down.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      t_right = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-t-right.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      t_left = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-t-left.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      cross = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-cross.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      ending_up = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-ending-up.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      ending_down = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-ending-down.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      ending_right = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-ending-right.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
      ending_left = {
        filename = "__long-distance-pipe__/assets/long-distance-pipe/pipe-ending-left.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
    },
    straight_vertical_single_visualization = ldPipe.pictures.straight_vertical_single_visualization,
    straight_vertical_visualization = ldPipe.pictures.straight_vertical_visualization,
    straight_vertical_window_visualization = ldPipe.pictures.straight_vertical_window_visualization,
    straight_horizontal_window_visualization = ldPipe.pictures.straight_horizontal_window_visualization,
    straight_horizontal_visualization = ldPipe.pictures.straight_horizontal_visualization,
    corner_up_right_visualization = ldPipe.pictures.corner_up_right_visualization,
    corner_up_left_visualization = ldPipe.pictures.corner_up_left_visualization,
    corner_down_right_visualization = ldPipe.pictures.corner_down_right_visualization,
    corner_down_left_visualization = ldPipe.pictures.corner_down_left_visualization,
    t_up_visualization = ldPipe.pictures.t_up_visualization,
    t_down_visualization = ldPipe.pictures.t_down_visualization,
    t_right_visualization = ldPipe.pictures.t_right_visualization,
    t_left_visualization = ldPipe.pictures.t_left_visualization,
    cross_visualization = ldPipe.pictures.cross_visualization,
    ending_up_visualization = ldPipe.pictures.ending_up_visualization,
    ending_down_visualization = ldPipe.pictures.ending_down_visualization,
    ending_right_visualization = ldPipe.pictures.ending_right_visualization,
    ending_left_visualization = ldPipe.pictures.ending_left_visualization,
    straight_vertical_single_disabled_visualization = ldPipe.pictures.straight_vertical_single_disabled_visualization,
    straight_vertical_disabled_visualization = ldPipe.pictures.straight_vertical_disabled_visualization,
    straight_vertical_window_disabled_visualization = ldPipe.pictures.straight_vertical_window_disabled_visualization,
    straight_horizontal_window_disabled_visualization = ldPipe.pictures.straight_horizontal_window_disabled_visualization,
    straight_horizontal_disabled_visualization = ldPipe.pictures.straight_horizontal_disabled_visualization,
    corner_up_right_disabled_visualization = ldPipe.pictures.corner_up_right_disabled_visualization,
    corner_up_left_disabled_visualization = ldPipe.pictures.corner_up_left_disabled_visualization,
    corner_down_right_disabled_visualization = ldPipe.pictures.corner_down_right_disabled_visualization,
    corner_down_left_disabled_visualization = ldPipe.pictures.corner_down_left_disabled_visualization,
    t_up_disabled_visualization = ldPipe.pictures.t_up_disabled_visualization,
    t_down_disabled_visualization = ldPipe.pictures.t_down_disabled_visualization,
    t_right_disabled_visualization = ldPipe.pictures.t_right_disabled_visualization,
    t_left_disabled_visualization = ldPipe.pictures.t_left_disabled_visualization,
    cross_disabled_visualization = ldPipe.pictures.cross_disabled_visualization,
    ending_up_disabled_visualization = ldPipe.pictures.ending_up_disabled_visualization,
    ending_down_disabled_visualization = ldPipe.pictures.ending_down_disabled_visualization,
    ending_right_disabled_visualization = ldPipe.pictures.ending_right_disabled_visualization,
    ending_left_disabled_visualization = ldPipe.pictures.ending_left_disabled_visualization,
    horizontal_window_background = ldPipe.pictures.horizontal_window_background,
    vertical_window_background = ldPipe.pictures.vertical_window_background,
    fluid_background = ldPipe.pictures.fluid_background,
    low_temperature_flow = ldPipe.pictures.low_temperature_flow,
    middle_temperature_flow = ldPipe.pictures.middle_temperature_flow,
    high_temperature_flow = ldPipe.pictures.high_temperature_flow,
    gas_flow = ldPipe.pictures.gas_flow,
}

data:extend({
    {
        type = "recipe",
        name = "ld-pipe",
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 1 },
        },
        results = { { type = "item", name = "ld-pipe", amount = 1 } },
    },
    {
        type = "item",
        name = "ld-pipe",
        icon = "__long-distance-pipe__/assets/icons/pipe.png",
        subgroup = "energy-pipe-distribution",        
        order = "a[pipe]-aa[ld-pipe]",
        place_result = "ld-pipe",
        stack_size = 100,
        weight = 5000,
    },
    ldPipe
})